
const SPOTS_DATA=[
['g1','gold',50,25],['g2','gold',44,34],['g3','gold',56,34],['g4','gold',49,43],['g5','gold',54,47],['g6','gold',43,51],['g7','gold',59,53],['g8','gold',51,60],
['w1','white',39,18],['w2','white',50,16],['w3','white',61,18],['w4','white',34,27],['w5','white',45,25],['w6','white',56,25],['w7','white',67,28],['w8','white',30,39],['w9','white',41,37],['w10','white',52,37],['w11','white',63,39],['w12','white',73,42],['w13','white',33,52],['w14','white',44,50],['w15','white',55,50],['w16','white',66,52],['w17','white',38,64],['w18','white',49,62],['w19','white',60,63],['w20','white',70,66],['w21','white',43,74],['w22','white',57,75],['w23','white',28,31],['w24','white',75,33],['w25','white',29,61],['w26','white',72,62],['w27','white',37,74],['w28','white',64,74],
['gr1','green',34,10],['gr2','green',45,8],['gr3','green',56,8],['gr4','green',67,11],['gr5','green',28,18],['gr6','green',73,20],['gr7','green',24,29],['gr8','green',77,31],['gr9','green',23,41],['gr10','green',78,42],['gr11','green',24,53],['gr12','green',77,54],['gr13','green',29,66],['gr14','green',72,67],['gr15','green',35,78],['gr16','green',66,79],['gr17','green',43,84],['gr18','green',57,84],['gr19','green',50,87],['gr20','green',32,38],['gr21','green',69,39],['gr22','green',35,49],['gr23','green',68,50],['gr24','green',39,59],['gr25','green',63,60],['gr26','green',42,69],['gr27','green',58,70],['gr28','green',30,76],['gr29','green',73,76],['gr30','green',26,48],['gr31','green',75,49],['gr32','green',31,22],['gr33','green',70,23],['gr34','green',40,13],['gr35','green',61,13],['gr36','green',50,11]
].map(([id,tier,x,y])=>({id,tier,x,y,claimed:false}));
const PRICES={gold:250,white:100,green:50},KEY='gtree_claims_v2';
let spots=[],selectedSpot=null;
const $=id=>document.getElementById(id);
const spotsLayer=$('spotsLayer'),tooltip=$('tooltip'),claimedCountEl=$('claimedCount'),form=$('claimForm'),submitBtn=$('submitBtn'),spotIdInput=$('spotIdInput'),latestBar=$('latestBar');
const goldLeftEl=$('goldLeft'),whiteLeftEl=$('whiteLeft'),greenLeftEl=$('greenLeft');
const hint=document.querySelector('.hint');
function init(){load();renderSpots();updateCount();renderLatest();bind();}
function load(){let saved=[];try{saved=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){};spots=SPOTS_DATA.map(s=>{const c=saved.find(x=>x.id===s.id);return c?{...s,...c,claimed:true}:{...s}})}
function save(){localStorage.setItem(KEY,JSON.stringify(spots.filter(s=>s.claimed).map(({id,name,url,tier,when})=>({id,name,url,tier,when}))))}
function renderSpots(){spotsLayer.innerHTML='';spots.forEach(s=>{const el=document.createElement('button');el.type='button';el.className=`spot ${s.tier}${s.claimed?' claimed':''}`;el.style.left=s.x+'%';el.style.top=s.y+'%';el.dataset.id=s.id;if(s.claimed)el.innerHTML=`<div class="leaf-avatar"><div class="avatar">${initials(s.name)}</div></div>`;el.onmouseenter=e=>showTip(e,s);el.onmousemove=moveTip;el.onmouseleave=hideTip;el.onclick=()=>s.claimed?openLink(s):selectSpot(s);spotsLayer.appendChild(el)})}
function showTip(e,s){tooltip.innerHTML=s.claimed?`<b>${esc(s.name||'Claimed')}</b><br><span>${cap(s.tier)} Spot</span>${s.url?`<br><span>${esc(s.url)}</span>`:''}`:`<b>${cap(s.tier)} Spot — $${PRICES[s.tier]}</b><br><span>Click to select this place</span>`;tooltip.classList.add('visible');moveTip(e)}
function moveTip(e){const r=spotsLayer.getBoundingClientRect();tooltip.style.left=e.clientX-r.left+'px';tooltip.style.top=e.clientY-r.top-12+'px';tooltip.style.transform='translate(-50%,-100%)'}
function hideTip(){tooltip.classList.remove('visible')}
function selectSpot(s){document.querySelectorAll('.spot.selected').forEach(x=>x.classList.remove('selected'));selectedSpot=s;spotIdInput.value=s.id;submitBtn.disabled=false;const el=document.querySelector(`.spot[data-id="${s.id}"]`);if(el)el.classList.add('selected');const radio=document.querySelector(`input[name="tier"][value="${s.tier}"]`);if(radio)radio.checked=true;if(hint){hint.classList.add('selected');hint.innerHTML=`Selected: <strong>${cap(s.tier)} Spot</strong> — $${PRICES[s.tier]}`}hideTip()}
function bind(){form.onsubmit=handleSubmit;document.querySelectorAll('input[name="tier"]').forEach(r=>r.onchange=()=>{if(selectedSpot&&selectedSpot.tier!==r.value)clearSelected()});const reset=$('resetDemo');if(reset)reset.onclick=()=>{localStorage.removeItem(KEY);selectedSpot=null;load();renderSpots();updateCount();renderLatest();clearSelected()}}
function clearSelected(){document.querySelectorAll('.spot.selected').forEach(x=>x.classList.remove('selected'));selectedSpot=null;spotIdInput.value='';submitBtn.disabled=true;if(hint){hint.classList.remove('selected');hint.innerHTML='🌿 <strong>Select a glowing dot</strong> on the tree to see price and claim that spot.'}}
function handleSubmit(e){e.preventDefault();if(!selectedSpot)return;const fd=new FormData(form),name=(fd.get('name')||'Your Brand').trim().slice(0,32),url=norm((fd.get('url')||'').trim()),tier=fd.get('tier');if(selectedSpot.tier!==tier){alert('Selected spot tier does not match.');return}if(!confirm(`Pay $${PRICES[tier]} for ${tier.toUpperCase()} spot?\n\nDemo payment — click OK.`))return;const s=spots.find(x=>x.id===selectedSpot.id);Object.assign(s,{claimed:true,name,url,when:Date.now()});save();renderSpots();updateCount();renderLatest();form.reset();clearSelected()}
function updateCount(){claimedCountEl.textContent=spots.filter(s=>s.claimed).length;if(goldLeftEl)goldLeftEl.textContent=spots.filter(s=>s.tier==='gold'&&!s.claimed).length;if(whiteLeftEl)whiteLeftEl.textContent=spots.filter(s=>s.tier==='white'&&!s.claimed).length;if(greenLeftEl)greenLeftEl.textContent=spots.filter(s=>s.tier==='green'&&!s.claimed).length}
function renderLatest(){const arr=spots.filter(s=>s.claimed).sort((a,b)=>(b.when||0)-(a.when||0)).slice(0,8);if(!arr.length){latestBar.innerHTML='<p class="empty-msg">No spots claimed yet. Be the first.</p>';return}latestBar.innerHTML=arr.map(s=>`<a class="claim-pill" href="${s.url||'#'}" ${s.url?'target="_blank" rel="noopener"':''}><span class="pill-dot ${s.tier}"></span><strong>${esc(s.name)}</strong><span class="pill-tier">claimed ${cap(s.tier)} Spot</span></a>`).join('')}
function openLink(s){if(s.url)window.open(s.url,'_blank','noopener')}
function norm(u){if(!u)return'';if(u.startsWith('@'))return'https://t.me/'+u.slice(1);return/^https?:\/\//i.test(u)?u:'https://'+u}
function initials(n){return String(n||'?').split(/\s+/).filter(Boolean).map(w=>w[0]).join('').slice(0,2).toUpperCase()}
function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
init();
